
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int T_FLOAT = 16;
  public static final int STORE = 8;
  public static final int ENTERO = 41;
  public static final int T_OBJECT = 20;
  public static final int DIFERENTE = 33;
  public static final int LLAVEDER = 22;
  public static final int FILTER = 7;
  public static final int T_INT = 15;
  public static final int UPDATE = 12;
  public static final int ASTERISCO = 31;
  public static final int NOT = 40;
  public static final int AND = 38;
  public static final int IGUAL = 30;
  public static final int CORDER = 26;
  public static final int USE = 3;
  public static final int OR = 39;
  public static final int BOOL = 43;
  public static final int ID = 45;
  public static final int IGUAL_IGUAL = 32;
  public static final int T_ARRAY = 19;
  public static final int DECIMAL = 42;
  public static final int EOF = 0;
  public static final int PARIZQ = 23;
  public static final int TABLE = 4;
  public static final int error = 1;
  public static final int COMA = 29;
  public static final int CADENA = 44;
  public static final int EXPORT = 10;
  public static final int ADD = 11;
  public static final int NULL = 46;
  public static final int MENOR = 37;
  public static final int FIELDS = 6;
  public static final int MAYOR = 36;
  public static final int T_STRING = 18;
  public static final int T_BOOL = 17;
  public static final int READ = 5;
  public static final int LLAVEIZQ = 21;
  public static final int MAYOR_IGUAL = 34;
  public static final int CLEAR = 14;
  public static final int DATABASE = 2;
  public static final int DOSP = 27;
  public static final int PTCOMA = 28;
  public static final int MENOR_IGUAL = 35;
  public static final int AT = 9;
  public static final int PARDER = 24;
  public static final int CORIZQ = 25;
  public static final int SET = 13;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DATABASE",
  "USE",
  "TABLE",
  "READ",
  "FIELDS",
  "FILTER",
  "STORE",
  "AT",
  "EXPORT",
  "ADD",
  "UPDATE",
  "SET",
  "CLEAR",
  "T_INT",
  "T_FLOAT",
  "T_BOOL",
  "T_STRING",
  "T_ARRAY",
  "T_OBJECT",
  "LLAVEIZQ",
  "LLAVEDER",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "DOSP",
  "PTCOMA",
  "COMA",
  "IGUAL",
  "ASTERISCO",
  "IGUAL_IGUAL",
  "DIFERENTE",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "MAYOR",
  "MENOR",
  "AND",
  "OR",
  "NOT",
  "ENTERO",
  "DECIMAL",
  "BOOL",
  "CADENA",
  "ID",
  "NULL"
  };
}

